version: "3"
services:
  app:
    build: .
    image: github_node
    environment:
      - NODE_INSPECT=0.0.0.0
    ports:
      - "80:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    entrypoint:
      - npm
      - run
      - dev:watch
  test:
    build: .
    image: github_node
    volumes:
      - .:/usr/src/app
    entrypoint:
      - npm
      - run
      - test